services:
  backend:
    build: .
    container_name: deepsound-backend
    environment:
      - PYTHONPATH=.
      - REDIS_URL=redis://redis_db:6379
    ports:
      - "5000:5000"
    volumes:
      - .:/deepsound
    depends_on:
      - redis_db
      - postgres_db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]


  redis_db:
    image: redis:7.2-alpine
    container_name: deepsound-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  postgres_db:
    container_name: deepsound-postgres
    image: postgres
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/18/docker

volumes:
  redis_data: